inicio
	varinicio
		A lit;
		B inteiro;
		D inteiro;
		C real;
	varfim;
{teste comentario asdfasdf}
	escreva "Digite B";
	leia B;
    escreva "Digite A:";
	leia A;
	se(B>2)
	entao
		se(B<=4)
		entao
			escreva "B esta entre 2 e 4";
		fimse
	fimse
    { comentado de novo pra teste}
	B<-B+1;
	B<-B+2;
	B<-B+3;
	D<-B;
	C<-5.0;

	escreva "\nB=\n";
	escreva D;
	escreva "\n";
	escreva C;
	escreva "\n";
	escreva A;

fim